# Generated by Django 3.2.8 on 2021-11-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalyst',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=50)),
                ('no_of_pass', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('speedo_start', models.IntegerField()),
                ('speedo_finish', models.IntegerField()),
            ],
        ),
    ]
