# Generated by Django 3.2.8 on 2022-02-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('driver', models.CharField(max_length=128)),
                ('plate_number', models.CharField(max_length=20)),
                ('start_location', models.CharField(max_length=256, null=True)),
                ('destinations1', models.CharField(max_length=256, null=True)),
                ('destinations2', models.CharField(blank=True, max_length=256, null=True)),
                ('destinations3', models.CharField(blank=True, max_length=256, null=True)),
                ('purpose', models.CharField(max_length=50)),
                ('no_of_pass', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mileage_start', models.IntegerField()),
                ('mileage_finish', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('round_trip', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=20)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
