# Generated by Django 3.2.9 on 2022-01-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='destination',
        ),
        migrations.AddField(
            model_name='journey',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journey',
            name='round_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_destination', models.CharField(max_length=256)),
                ('other_destinations', models.ManyToManyField(related_name='_main_destinations_other_destinations_+', to='main.Destinations')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='destinations',
            field=models.ManyToManyField(to='main.Destinations'),
        ),
    ]
